### ISSUE TITLE
ept serve --root not use

### ISSUE THREAD

**Issue by moshangyeyu** [connormanning/ept-tools#17]
now in v0.0.8,when i input ept serve -- root D:\annotation_data\data_management\test\ept\red-rocks,i get Arguments root and roots are mutually exclusive
Options:
      --version   Show version number                                  [boolean]
      --help      Show help                                            [boolean]
      --root      EPT project directory to serve                        [string]
      --roots     Allowed endpoint roots - "*" for anything [array] [default: ["*"]]
  -p, --port      Server port                           [number] [default: 3000]
      --origins   Access-Control-Allow-Origin list      [array] [default: ["*"]]
      --keyfile   SSL key file                                          [string]
      --certfile  SSL cert file                                         [string]
      --cafile    SSL CA file                                           [string]

when i input ept serve -- roots D:\annotation_data\data_management\test\ept,i don't know how to visit tileset.json or ept.json
when i visit http://localhost:3000/red-rocks/ept-tileset/tileset.json, i get {"message":"Missing required \"ept\" parameter"}
ept serve --help It's not the same as the document description,your docment like this, not have roots
ept serve --help

Serve 3D Tiles on the fly from EPT resources

Options:
      --version   Show version number                                  [boolean]
      --help      Show help                                            [boolean]
      --root      EPT project directory to serve         [string] [default: "."]
  -p, --port      Server port                           [number] [default: 3000]
      --origins   Access-Control-Allow-Origin list       [string] [default: "*"]
      --keyfile   SSL key file                                          [string]
      --certfile  SSL cert file                                         [string]
      --cafile    SSL CA file                                           [string]
what shoud i do,thank you

**Comment by arruga** [comment]
Thank you Connor Manning for this tool. 

I think I have the same problem with ept serve. 

I have an entwine forder with a few Entwine point clouds in subfolders: red-rocks, lidardat1, tarragona_centre...

Option -root seems not working. I also get "Arguments root and roots are mutually exclusive"

When I run 
ept serve -roots "/dades/entwine" 
the server seems to start properly. It answers:
Roots: [ '/dades/entwine' ]
Port: 3000
Allowed origins: *

But from my application I receive a return code 400 to the GET request. 
RequestErrorEvent {statusCode: 400, response: "{\"message\":\"Missing required \\\"ept\\\" parameter\"}", responseHeaders: {…}}
response: "{\"message\":\"Missing required \\\"ept\\\" parameter\"}"
responseHeaders: {content-length: "48", content-type: "application/json; charset=utf-8"}
statusCode: 400
__proto__: Object
My Cesium call is:
Cesium.Cesium3DTileset({
url : "http://172.30.28.33:3000/red-rocks/ept-tileset/tileset.json",
})

I have been able to translate my tarragona_centre Entwine point cloud to a 3DTiles point cloud with ept tile using the --truncate parameter and the application works nicely after adapting the url.

**Comment by connormanning** [comment]
Hey - sorry I missed this issue.  Please see updated information [here](https://github.com/connormanning/ept-tools/blob/master/doc/serve.md#ept-serve) from the new release `0.0.10` and give it another shot after upgrading.  Please re-open this issue or feel free to make a new one if there are any problems.  The URLs look a little bit different now, note that there is an `ept` query parameter which selects the proper EPT dataset to be converted.
