### ISSUE TITLE
SRS definitions

### ISSUE THREAD

**Issue by connormanning** [connormanning/ept-tools#5]
Currently only UTM zones, web-mercator, lon-lat, and ECEF are supported, with some other one-offs (see [here](https://github.com/connormanning/ept-tools/blob/master/src/proj.js#L44)).  Other definitions should be added, preferably from an EPSG code database somewhere rather than one-offs.

**Comment by connormanning** [comment]
In the meantime, users should feel free to submit PRs for one-off SRS definitions and I'll merge them.  This will be helpful in the future if we replace them from a DB to preserve any SRS definitions that people are using.

**Comment by hobu** [comment]
[codes.json.zip](https://github.com/connormanning/ept-tools/files/3628556/codes.json.zip)
